import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

//ADDED FONT
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

//META DATA
export const metadata: Metadata = {
  title: "NEXT14 WITH AUTHJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
